# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/w/wngrya001/Desktop/RUNTHIS/PID_Generation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/w/wngrya001/Desktop/RUNTHIS/PID_Generation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/w/wngrya001/Desktop/RUNTHIS/PID_Generation/CMakeFiles /home/w/wngrya001/Desktop/RUNTHIS/PID_Generation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/w/wngrya001/Desktop/RUNTHIS/PID_Generation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pid_gen

# Build rule for target.
pid_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pid_gen
.PHONY : pid_gen

# fast build rule for target.
pid_gen/fast:
	$(MAKE) -f CMakeFiles/pid_gen.dir/build.make CMakeFiles/pid_gen.dir/build
.PHONY : pid_gen/fast

#=============================================================================
# Target rules for targets named pid_lib

# Build rule for target.
pid_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pid_lib
.PHONY : pid_lib

# fast build rule for target.
pid_lib/fast:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/build
.PHONY : pid_lib/fast

DataRetrieval.o: DataRetrieval.cpp.o
.PHONY : DataRetrieval.o

# target to build an object file
DataRetrieval.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/DataRetrieval.cpp.o
.PHONY : DataRetrieval.cpp.o

DataRetrieval.i: DataRetrieval.cpp.i
.PHONY : DataRetrieval.i

# target to preprocess a source file
DataRetrieval.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/DataRetrieval.cpp.i
.PHONY : DataRetrieval.cpp.i

DataRetrieval.s: DataRetrieval.cpp.s
.PHONY : DataRetrieval.s

# target to generate assembly for a file
DataRetrieval.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/DataRetrieval.cpp.s
.PHONY : DataRetrieval.cpp.s

Links.o: Links.cpp.o
.PHONY : Links.o

# target to build an object file
Links.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Links.cpp.o
.PHONY : Links.cpp.o

Links.i: Links.cpp.i
.PHONY : Links.i

# target to preprocess a source file
Links.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Links.cpp.i
.PHONY : Links.cpp.i

Links.s: Links.cpp.s
.PHONY : Links.s

# target to generate assembly for a file
Links.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Links.cpp.s
.PHONY : Links.cpp.s

Neuron.o: Neuron.cpp.o
.PHONY : Neuron.o

# target to build an object file
Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Neuron.cpp.o
.PHONY : Neuron.cpp.o

Neuron.i: Neuron.cpp.i
.PHONY : Neuron.i

# target to preprocess a source file
Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Neuron.cpp.i
.PHONY : Neuron.cpp.i

Neuron.s: Neuron.cpp.s
.PHONY : Neuron.s

# target to generate assembly for a file
Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/Neuron.cpp.s
.PHONY : Neuron.cpp.s

NeuronLayers.o: NeuronLayers.cpp.o
.PHONY : NeuronLayers.o

# target to build an object file
NeuronLayers.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/NeuronLayers.cpp.o
.PHONY : NeuronLayers.cpp.o

NeuronLayers.i: NeuronLayers.cpp.i
.PHONY : NeuronLayers.i

# target to preprocess a source file
NeuronLayers.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/NeuronLayers.cpp.i
.PHONY : NeuronLayers.cpp.i

NeuronLayers.s: NeuronLayers.cpp.s
.PHONY : NeuronLayers.s

# target to generate assembly for a file
NeuronLayers.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/NeuronLayers.cpp.s
.PHONY : NeuronLayers.cpp.s

ParticleInformation.o: ParticleInformation.cpp.o
.PHONY : ParticleInformation.o

# target to build an object file
ParticleInformation.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/ParticleInformation.cpp.o
.PHONY : ParticleInformation.cpp.o

ParticleInformation.i: ParticleInformation.cpp.i
.PHONY : ParticleInformation.i

# target to preprocess a source file
ParticleInformation.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/ParticleInformation.cpp.i
.PHONY : ParticleInformation.cpp.i

ParticleInformation.s: ParticleInformation.cpp.s
.PHONY : ParticleInformation.s

# target to generate assembly for a file
ParticleInformation.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/ParticleInformation.cpp.s
.PHONY : ParticleInformation.cpp.s

RunProgram.o: RunProgram.cpp.o
.PHONY : RunProgram.o

# target to build an object file
RunProgram.cpp.o:
	$(MAKE) -f CMakeFiles/pid_gen.dir/build.make CMakeFiles/pid_gen.dir/RunProgram.cpp.o
.PHONY : RunProgram.cpp.o

RunProgram.i: RunProgram.cpp.i
.PHONY : RunProgram.i

# target to preprocess a source file
RunProgram.cpp.i:
	$(MAKE) -f CMakeFiles/pid_gen.dir/build.make CMakeFiles/pid_gen.dir/RunProgram.cpp.i
.PHONY : RunProgram.cpp.i

RunProgram.s: RunProgram.cpp.s
.PHONY : RunProgram.s

# target to generate assembly for a file
RunProgram.cpp.s:
	$(MAKE) -f CMakeFiles/pid_gen.dir/build.make CMakeFiles/pid_gen.dir/RunProgram.cpp.s
.PHONY : RunProgram.cpp.s

SumPIDCalculation.o: SumPIDCalculation.cpp.o
.PHONY : SumPIDCalculation.o

# target to build an object file
SumPIDCalculation.cpp.o:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/SumPIDCalculation.cpp.o
.PHONY : SumPIDCalculation.cpp.o

SumPIDCalculation.i: SumPIDCalculation.cpp.i
.PHONY : SumPIDCalculation.i

# target to preprocess a source file
SumPIDCalculation.cpp.i:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/SumPIDCalculation.cpp.i
.PHONY : SumPIDCalculation.cpp.i

SumPIDCalculation.s: SumPIDCalculation.cpp.s
.PHONY : SumPIDCalculation.s

# target to generate assembly for a file
SumPIDCalculation.cpp.s:
	$(MAKE) -f CMakeFiles/pid_lib.dir/build.make CMakeFiles/pid_lib.dir/SumPIDCalculation.cpp.s
.PHONY : SumPIDCalculation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pid_gen"
	@echo "... pid_lib"
	@echo "... rebuild_cache"
	@echo "... DataRetrieval.o"
	@echo "... DataRetrieval.i"
	@echo "... DataRetrieval.s"
	@echo "... Links.o"
	@echo "... Links.i"
	@echo "... Links.s"
	@echo "... Neuron.o"
	@echo "... Neuron.i"
	@echo "... Neuron.s"
	@echo "... NeuronLayers.o"
	@echo "... NeuronLayers.i"
	@echo "... NeuronLayers.s"
	@echo "... ParticleInformation.o"
	@echo "... ParticleInformation.i"
	@echo "... ParticleInformation.s"
	@echo "... RunProgram.o"
	@echo "... RunProgram.i"
	@echo "... RunProgram.s"
	@echo "... SumPIDCalculation.o"
	@echo "... SumPIDCalculation.i"
	@echo "... SumPIDCalculation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

